### ISSUE TITLE
The ng build -prod doesn't work in restaurant web app

### ISSUE THREAD

**Issue by amanganiello90** [ionicfirebaseapp/restaurantapp#1]
In the last resturant web app version download on Febrary, the ng build --prod fails with this error:

**ERROR in Error: TypeError: Cannot read property 'kind' of undefined**

I have fixed it with:  **yarn add typescript@2.7.2 --save-dev** , but now in the build there is this warning..

@angular/compiler-cli@5.0.0 requires typescript@'>=2.4.2 <2.5.0' but 2.7.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.5.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".

Update the compiler-cli breaks another things.

So any suggestion to resolve this warning that could be dangerous (it is a typescript and compiler version)?

**Comment by PietechSolution** [comment]
ng build --prod --no-aot

**Comment by amanganiello90** [comment]
Thanks, it works
