### ISSUE TITLE
pre-selling question 

### ISSUE THREAD

**Issue by NuruddinBadawi** [ionicfirebaseapp/restaurantapp#3]
- is the version you are selling using ionic 4  or 3?
- is it the CMS come with the purchase or separately?
- I need a feature that let me create a menu for each day and specify what the food in this menu, so the user can see the whole week menu schedule because of my restaurant offers varied dishes every day, so is it possible or you can offer it to me with an extra price? 
- also, I want to integrate phone number authentication instead of email, is it possible and what is the best backend I can offer this service, firebase or nodeJs ?

what do you think?

**Comment by PietechSolution** [comment]
Please drop Email on info@ionicfirebaseapp.com or share your Email ID.

**Comment by NuruddinBadawi** [comment]
nourba691@gmail.com
